[package]
name = "jpeg-decoder"
version = "0.1.15"
authors = ["Ulf Nilsson <kaksmet@gmail.com>"]
description = "JPEG decoder"
documentation = "https://docs.rs/jpeg-decoder"
repository = "https://github.com/kaksmet/jpeg-decoder"
readme = "README.md"
keywords = ["jpeg", "jpg", "decoder", "image"]
license = "MIT / Apache-2.0"
exclude = ["tests/*", "/sgx/*"]

[dependencies]
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx" }
rayon = { version = "1.0", optional = true }
sgx_tstd = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk.git", optional = true }

[dev-dependencies]
png = "0.14"
walkdir = "2.0"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
